export const REISEIVE_HOMEDATA = 'reiseive_homedata'
export const REISEIVE_CATEGORY = 'reiseive_category'
export const REISEIVE_TUIJIAN = 'reiseive_tuijian'
export const REISEIVE_HOTKEWORD = 'reiseive_hotlist'
export const REISEIVE_SERCHKEYWORD = 'reiseive_serchkeyword'
export const REISEIVE_PAGELIST = 'reiseive_pagelist'